# Generated by Django 5.2.7 on 2025-10-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringanalysis',
            name='value',
            field=models.TextField(unique=True),
        ),
    ]
