# Generated by Django 5.2.7 on 2025-10-22 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strings', '0002_alter_stringanalysis_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringanalysis',
            name='sha256_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
